# Converting Raw Scraped Data into a Pandas Dataframe
1. Read the csv file

In [45]:
import pandas as pd

df = pd.read_csv("../data/raw/players.csv")
df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1021 entries, 0 to 1020
Columns: 120 entries, League to Shots Per Goal Scored
dtypes: float64(97), int64(1), str(22)
memory usage: 957.3 KB

2. Remove unwanted columns

In [46]:
cols_to_drop = [
    "Hit The Woodwork",
    "Hit The Woodwork (Per90)",
    "Hat-tricks",
    "3 or More Goals",
    "2 or More Goals",
    "Annual Salary (Per90)",
    "Red Cards (Per90)",
    "Yellow Cards (Per90)",
    "Matches Subbed Out",
    "Matches Subbed Out (Per90)",
    "Matches Subbed In",
    "Matches Subbed In (Per90)",
    "Matches Started (Per90)",
]

df = df.drop(columns=cols_to_drop)
df

,League,Team,Name,Age,Position,Market Value,Footystats URL,Matches Played,Matches Played (Per90),Minutes,...,Punches (Per90),Shot Conversion Rate,Shots Taken,Shots Taken (Per90),Shots On Target,Shots On Target (Per90),Shots Off Target,Shots Off Target (Per90),Shot Accuracy,Shots Per Goal Scored
0,premier-league,Manchester City,Gianluigi Donnarumma,27,Goalkeeper,€45.00m,https://footystats.org/players/italy/gianluigi...,28.0,NaN,2520.0,...,0.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,premier-league,Manchester City,James Trafford,23,Goalkeeper,€25.00m,https://footystats.org/players/england/james-t...,31.0,NaN,2790.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,premier-league,Manchester City,Marcus Bettinelli,33,Goalkeeper,€500k,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,premier-league,Manchester City,Josko Gvardiol,24,Centre-Back,€70.00m,https://footystats.org/players/croatia/josko-g...,16.0,NaN,1304.0,...,NaN,11.76,17.0,1.17,5.0,0.35,12.0,0.83,29.41,8.50
4,premier-league,Manchester City,Marc Guéhi,25,Centre-Back,€65.00m,https://footystats.org/players/england/marc-guehi,29.0,NaN,2610.0,...,NaN,10.71,28.0,0.97,8.0,0.28,20.0,0.69,28.57,9.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1016,la-liga,Real Oviedo,Ovie Ejaria,28,Left Winger,€500k,https://footystats.org/players/england/oviemun...,7.0,NaN,179.0,...,NaN,33.33,6.0,0.27,1.0,0.07,5.0,0.33,83.33,3.00
1017,la-liga,Real Oviedo,Haissem Hassan,24,Right Winger,€4.00m,NaN,NaN,NaN,NaN,...,NaN,0.00,5.0,1.69,1.0,0.66,6.0,0.67,38.71,7.75
1018,la-liga,Real Oviedo,Federico Viñas,27,Centre-Forward,€4.00m,https://footystats.org/players/italy/federico-...,23.0,NaN,275.0,...,NaN,5.88,6.0,0.82,1.0,0.22,5.0,0.41,33.33,17.00
1019,la-liga,Real Oviedo,Thiago Borbas,24,Centre-Forward,€4.00m,https://footystats.org/players/uruguay/thiago-...,7.0,NaN,82.0,...,NaN,0.00,23.0,0.82,6.0,0.20,11.0,0.56,21.74,4.25
1020,la-liga,Real Oviedo,Álex Forés,25,Centre-Forward,€800k,NaN,NaN,NaN,NaN,...,NaN,20.00,5.0,0.72,2.0,0.09,5.0,0.53,21.74,15.00

3. Remove players without stats

In [47]:
df = df[df["Footystats URL"].notna()]
df = df.drop(columns=["Footystats URL"])

df.to_pickle("../data/raw/raw_df.pkl")
df

,League,Team,Name,Age,Position,Market Value,Matches Played,Matches Played (Per90),Minutes,Minutes (Per90),...,Punches (Per90),Shot Conversion Rate,Shots Taken,Shots Taken (Per90),Shots On Target,Shots On Target (Per90),Shots Off Target,Shots Off Target (Per90),Shot Accuracy,Shots Per Goal Scored
0,premier-league,Manchester City,Gianluigi Donnarumma,27,Goalkeeper,€45.00m,28.0,NaN,2520.0,90 min' per appearance,...,0.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,premier-league,Manchester City,James Trafford,23,Goalkeeper,€25.00m,31.0,NaN,2790.0,90 min' per appearance,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,premier-league,Manchester City,Josko Gvardiol,24,Centre-Back,€70.00m,16.0,NaN,1304.0,82 min' per appearance,...,NaN,11.76,17.0,1.17,5.0,0.35,12.0,0.83,29.41,8.50
4,premier-league,Manchester City,Marc Guéhi,25,Centre-Back,€65.00m,29.0,NaN,2610.0,90 min' per appearance,...,NaN,10.71,28.0,0.97,8.0,0.28,20.0,0.69,28.57,9.33
5,premier-league,Manchester City,Rúben Dias,28,Centre-Back,€60.00m,25.0,NaN,2051.0,82 min' per appearance,...,NaN,20.00,10.0,0.44,4.0,0.18,6.0,0.26,40.00,5.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014,la-liga,Real Oviedo,Thiago Fernández,22,Left Winger,€4.50m,7.0,NaN,82.0,12 min' per appearance,...,NaN,33.33,6.0,0.27,1.0,0.07,5.0,0.33,16.67,0.00
1015,la-liga,Real Oviedo,Ilyas Chaira,25,Left Winger,€4.00m,29.0,NaN,1939.0,67 min' per appearance,...,NaN,33.33,6.0,0.40,1.0,0.22,5.0,0.33,16.67,3.00
1016,la-liga,Real Oviedo,Ovie Ejaria,28,Left Winger,€500k,7.0,NaN,179.0,26 min' per appearance,...,NaN,33.33,6.0,0.27,1.0,0.07,5.0,0.33,83.33,3.00
1018,la-liga,Real Oviedo,Federico Viñas,27,Centre-Forward,€4.00m,23.0,NaN,275.0,12 min' per appearance,...,NaN,5.88,6.0,0.82,1.0,0.22,5.0,0.41,33.33,17.00
1019,la-liga,Real Oviedo,Thiago Borbas,24,Centre-Forward,€4.00m,7.0,NaN,82.0,12 min' per appearance,...,NaN,0.00,23.0,0.82,6.0,0.20,11.0,0.56,21.74,4.25